# Generated by Django 4.2.7 on 2023-11-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebankapp", "0002_alter_registration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="mail_id",
            field=models.EmailField(default="qwerty@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
